R1:
  hostname: 192.168.233.19
  port: 22
  connection_options:
    netmiko:
      extras:
        secret: cisco
        session_log: ~/host1.log
  username: admin
  password: cisco
  platform: ios
  groups:
    - usa
  data:
    site: usa
    role: tor
    type: router
R2:
  hostname: 192.168.233.10
  port: 22
  connection_options:
    netmiko:
      extras:
        secret: cisco
        session_log: ~/host2.log
  username: admin
  password: cisco
  platform: ios
  groups:
      - usa
  data:
    site: usa
    role: wan
    type: router
